### ISSUE TITLE
Problema instalando versión 12.00 addon SII IGIC

### ISSUE THREAD

**Issue by raulbm** [sistemasdedatos/odoo-addons#4]
Hola Rodrigo,
Este fin de semana he estado intentando probar el módulo de SII para IGIC que habéis publicado v12, pero tengo la sensación de que no son funcionales.
En los comentarios del commit de la rama para la versión 12.0 se lee
"[12.0] ADD Branch: modules not install" y en apariencia el código es el mismo que para la v10.0
¿Me lo puedes confirmar?
Un saludo cordial
Raúl Benavente

**Comment by rodrig92** [comment]
Buenos días Raúl,
Efectivamente, está en v10, si te fijas en el __manifest__ está como no instalable. 
El módulo lo migraremos a v12, de momento no hemos tenido la necesidad.
Seguramente a comienzos del 2020 nos meteremos de lleno en ese asunto, de todas formas, siempre es bienvenido un PR ;).
Un saludo.
Rodrigo.

**Comment by raulbm** [comment]
Muchísimas gracias Rodrigo por la respuesta. 

Estamos por implementar en nuestra empresa Odoo y la única pega que le hemos encontrado es la adaptación para el IGIC y el SII de la ATC.  

Nuestra idea podría ser implantarlo durante el primer trimestre del ejercicio 2020 y no nos importaría ayudar a migrarlo a la v12, pero dado que somos newbies con Odoo se apreciaría mucho ayuda en el sentido de orientar nuestros pasos. 

¿Serian estos los módulos a migrar?
l10n_es_aeat_mod420 
l10n_es_aeat_sii_igic 
l10n_es_aeat_sii_igic_dua 
l10n_es_aeat_sii_pos_igic 
l10n_es_igic

Por otra parte, ¿estimas realista con el plazo que nos hemos propuesto para la implementación en nuestra empresa el desarrollo de estas migraciones?

¿Qué cambios requieren las migraciones? modelo de datos, views, …

Muchas gracias anticipadas

**Comment by rodrig92** [comment]
Entiendo que se trata de una gran empresa (más de 6 millones de facturación anual) en otro caso  no les haría falta el SII, aunque se supone que en un periodo no muy largo, será obligatorio para todo tipo de empresa.

El módulo l10n_es_igic está migrado ya, lo que aún no lo han mezclado en la rama 12.0 (https://github.com/OCA/l10n-spain/pull/1097). Tengan en cuenta que, el año que viene vuelven a subir el porcentaje impositivo.

El módulo l10n_es_aeat_sii_pos_igic es únicamente si utilizan TPV, si no es así, no es necesario.
El del 420, si están sujetos a SII, casi que tampoco lo necesitan, lo único que hace (resumiendo mucho) es generar el PDF con el modelo trimestral para la ATC.

Los módulos a trasladar serían l10n_es_aeat_sii_igic y l10n_es_aeat_sii_igic_dua. Es importante destacar que dependen de los módulos del SII de Acysos, y no de los de OCA. Si quieren hacer unos módulos que acepte OCA habría que rehacer y no migrar.

Por último, con respecto a los plazos, siendo nuevos en Odoo, efectivamente lo veo bastante optimista. Es importante para una implantación conocer el producto que estamos instalando o apoyarnos en alguna empresa que lo conozca. Nosotros nos hemos encontrado casos de implantaciones con desarrollos a medida que ya el propio Odoo contemplaba de base, desarrollados por falta de comprensión de la herramienta.

Un saludo.
